### ISSUE TITLE
ImportError with jwt

### ISSUE THREAD

**Issue by vogt31337** [Septem151/Flask_PyJWT#2]
Freshly installed and got this error:

```
Traceback (most recent call last):
  File "E:\git\opsim_web_ui\server.py", line 2, in <module>
    from flask_pyjwt import AuthManager, current_token, require_token
  File "C:\ProgramData\Anaconda3\envs\opsim_web\Lib\site-packages\flask_pyjwt\__init__.py", line 7, in <module>
    from .jwt import JWT as JWT
  File "C:\ProgramData\Anaconda3\envs\opsim_web\Lib\site-packages\flask_pyjwt\jwt.py", line 7, in <module>
    from jwt import decode as pyjwt_decode
ImportError: cannot import name 'decode' from 'jwt' (C:\ProgramData\Anaconda3\envs\opsim_web\Lib\site-packages\jwt\__init__.py)
```

I think the JWT guys changed their lib so that you have to instance a JWT object.

**Comment by vogt31337** [comment]
Solved the issue, there was jwt installed and pyjwt. This lib depends on pyjwt and not jwt. So uninstalling jwt solved the issue.
